# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ade09a6907a1c1faa82bbf565e63ce7bc61f559a2a116f23564d561bfdb63b0c11dfeabd61585b5f9c99645c6a5aba88a9ba9463c4f2d8539181062a69c06ac

test:
  secret_key_base: 505f96554fababe721fe9bb8c27cf28305c05b121931f3799b642aa293b24edfd4e960e3f3555d3f0960aafec16d54ba2c41fcc23073d55254b584687b152fd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
